# This is a basic workflow to help you get started with Actions

name: Python testing

# Controls when the action will run.
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python $${{ matrix.python-version }}
        uses: action/setup-python@v2
        with:
          python-version: $${{ matrix.python-verion }}

      - name: Install
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Testing
        run: python -m unittest discover